/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Entries */
        get: operations["list_audit_entries_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigations */
        get: operations["list_investigations_api_investigations_get"];
        put?: never;
        /** Create Investigation */
        post: operations["create_investigation_api_investigations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/assignable-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assignable Users */
        get: operations["assignable_users_api_investigations_assignable_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation */
        get: operations["get_investigation_api_investigations__reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Investigation */
        patch: operations["update_investigation_api_investigations__reference__patch"];
        trace?: never;
    };
    "/api/investigations/{reference}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_investigations__reference__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_api_investigations__reference__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{reference}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Investigation Activity */
        get: operations["investigation_activity_api_investigations__reference__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence */
        get: operations["list_evidence_api_investigations__case_reference__evidence_get"];
        put?: never;
        /** Upload Evidence */
        post: operations["upload_evidence_api_investigations__case_reference__evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_investigations__case_reference__evidence__evidence_reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Original
         * @description The original file, always as a download (never rendered by the browser).
         */
        get: operations["download_original_api_investigations__case_reference__evidence__evidence_reference__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview
         * @description A derived JPEG preview (images only). The original is never served inline.
         */
        get: operations["preview_api_investigations__case_reference__evidence__evidence_reference__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}/verify-integrity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Integrity */
        post: operations["verify_integrity_api_investigations__case_reference__evidence__evidence_reference__verify_integrity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Status */
        post: operations["change_status_api_investigations__case_reference__evidence__evidence_reference__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocess */
        post: operations["reprocess_api_investigations__case_reference__evidence__evidence_reference__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence History */
        get: operations["evidence_history_api_investigations__case_reference__evidence__evidence_reference__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignableUser */
        AssignableUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /** AuditEntry */
        AuditEntry: {
            /** Id */
            id: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Actor Email */
            actor_email: string | null;
            /** Action */
            action: string;
            /** Object Type */
            object_type: string | null;
            /** Object Id */
            object_id: string | null;
            /** Previous State */
            previous_state: {
                [key: string]: unknown;
            } | null;
            /** New State */
            new_state: {
                [key: string]: unknown;
            } | null;
            /** Note */
            note: string | null;
            /** Ip Address */
            ip_address: string | null;
        };
        /** Body_upload_evidence_api_investigations__case_reference__evidence_post */
        Body_upload_evidence_api_investigations__case_reference__evidence_post: {
            /**
             * File
             * @description The evidence file
             */
            file: string;
            /**
             * Evidence Type
             * @enum {string}
             */
            evidence_type: "video" | "image" | "document" | "gps" | "mobile" | "call_records" | "financial" | "vehicle" | "witness_statement" | "digital_file" | "other";
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Collected At */
            collected_at?: string | null;
            /**
             * Location Text
             * @default
             */
            location_text: string;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Tags
             * @description Comma-separated
             * @default
             */
            tags: string;
        };
        /** CurrentUserResponse */
        CurrentUserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Permissions */
            permissions: string[];
            /** Mfa Enabled */
            mfa_enabled: boolean;
            /**
             * Session Expires At
             * Format: date-time
             */
            session_expires_at: string;
        };
        /** DatabaseHealth */
        DatabaseHealth: {
            /** Connected */
            connected: boolean;
            /** Server Version */
            server_version?: string | null;
            /**
             * Extensions
             * @default {}
             */
            extensions: {
                [key: string]: string | null;
            };
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Reference */
            reference: string;
            /** Investigation Reference */
            investigation_reference: string;
            /**
             * Evidence Type
             * @enum {string}
             */
            evidence_type: "video" | "image" | "document" | "gps" | "mobile" | "call_records" | "financial" | "vehicle" | "witness_statement" | "digital_file" | "other";
            /**
             * Status
             * @enum {string}
             */
            status: "uploaded" | "processing" | "processed" | "verified" | "requires_review" | "archived";
            /** Source */
            source: string;
            /** Description */
            description: string;
            /** Collected At */
            collected_at: string | null;
            /** Location Text */
            location_text: string;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            /** Tags */
            tags: string[];
            /** Original Filename */
            original_filename: string;
            /** Media Type */
            media_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /** Integrity Checked At */
            integrity_checked_at: string | null;
            /** Integrity Ok */
            integrity_ok: boolean | null;
            /** Has Preview */
            has_preview: boolean;
            /** File Metadata */
            file_metadata: {
                [key: string]: unknown;
            };
            /** Uploaded By */
            uploaded_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            latest_job: components["schemas"]["JobOut"] | null;
        };
        /** EvidencePage */
        EvidencePage: {
            /** Items */
            items: components["schemas"]["EvidenceOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            database: components["schemas"]["DatabaseHealth"];
        };
        /**
         * InvestigationCounts
         * @description Filled in as later phases add evidence (P5), entities/events (P6), correlations (P8).
         */
        InvestigationCounts: {
            /**
             * Evidence
             * @default 0
             */
            evidence: number;
            /**
             * Entities
             * @default 0
             */
            entities: number;
            /**
             * Events
             * @default 0
             */
            events: number;
            /**
             * Correlations
             * @default 0
             */
            correlations: number;
        };
        /** InvestigationCreate */
        InvestigationCreate: {
            /** Title */
            title: string;
            /** Case Type */
            case_type: string;
            /**
             * Priority
             * @default medium
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "critical";
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Tags */
            tags?: string[];
        };
        /** InvestigationOut */
        InvestigationOut: {
            /** Reference */
            reference: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Case Type */
            case_type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "active" | "under_review" | "suspended" | "closed" | "archived";
            /**
             * Priority
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "critical";
            /**
             * Stage
             * @enum {string}
             */
            stage: "intake" | "processing" | "extraction" | "correlation" | "review" | "reporting" | "closed";
            /** Location */
            location: string;
            /** Tags */
            tags: string[];
            lead_investigator: components["schemas"]["PersonRef"];
            /** Team Size */
            team_size: number;
            /** My Role In Case */
            my_role_in_case: ("lead" | "member") | null;
            counts: components["schemas"]["InvestigationCounts"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** InvestigationPage */
        InvestigationPage: {
            /** Items */
            items: components["schemas"]["InvestigationOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** InvestigationUpdate */
        InvestigationUpdate: {
            /** Title */
            title?: string | null;
            /** Case Type */
            case_type?: string | null;
            /** Priority */
            priority?: ("low" | "medium" | "high" | "critical") | null;
            /** Status */
            status?: ("draft" | "active" | "under_review" | "suspended" | "closed" | "archived") | null;
            /** Stage */
            stage?: ("intake" | "processing" | "extraction" | "correlation" | "review" | "reporting" | "closed") | null;
            /** Location */
            location?: string | null;
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Progress */
            progress: number;
            /** Current Step */
            current_step: string | null;
            /** Steps */
            steps: components["schemas"]["JobStep"][];
            /** Attempts */
            attempts: number;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** JobStep */
        JobStep: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Duration Ms */
            duration_ms: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Remember
             * @default false
             */
            remember: boolean;
        };
        /** MemberAdd */
        MemberAdd: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** MemberOut */
        MemberOut: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /**
             * Role In Case
             * @enum {string}
             */
            role_in_case: "lead" | "member";
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
        };
        /** PersonRef */
        PersonRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
        };
        /** StatusChange */
        StatusChange: {
            /**
             * Status
             * @enum {string}
             */
            status: "processed" | "verified" | "requires_review";
            /** Note */
            note?: string | null;
        };
        /** UserSummary */
        UserSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Mfa Enabled */
            mfa_enabled: boolean;
            /** Locked */
            locked: boolean;
            /** Last Login At */
            last_login_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"][];
                };
            };
        };
    };
    list_audit_entries_api_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigations_api_investigations_get: {
        parameters: {
            query?: {
                search?: string | null;
                status?: ("draft" | "active" | "under_review" | "suspended" | "closed" | "archived") | null;
                priority?: ("low" | "medium" | "high" | "critical") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_investigation_api_investigations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assignable_users_api_investigations_assignable_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignableUser"][];
                };
            };
        };
    };
    get_investigation_api_investigations__reference__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_investigation_api_investigations__reference__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_investigations__reference__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_investigations__reference__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investigation_activity_api_investigations__reference__activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_api_investigations__case_reference__evidence_get: {
        parameters: {
            query?: {
                search?: string | null;
                evidence_type?: ("video" | "image" | "document" | "gps" | "mobile" | "call_records" | "financial" | "vehicle" | "witness_statement" | "digital_file" | "other") | null;
                status?: ("uploaded" | "processing" | "processed" | "verified" | "requires_review" | "archived") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                case_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_evidence_api_investigations__case_reference__evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_evidence_api_investigations__case_reference__evidence_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_investigations__case_reference__evidence__evidence_reference__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_original_api_investigations__case_reference__evidence__evidence_reference__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_investigations__case_reference__evidence__evidence_reference__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_integrity_api_investigations__case_reference__evidence__evidence_reference__verify_integrity_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_api_investigations__case_reference__evidence__evidence_reference__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_api_investigations__case_reference__evidence__evidence_reference__reprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_history_api_investigations__case_reference__evidence__evidence_reference__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
