/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Entries */
        get: operations["list_audit_entries_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigations */
        get: operations["list_investigations_api_investigations_get"];
        put?: never;
        /** Create Investigation */
        post: operations["create_investigation_api_investigations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/assignable-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assignable Users */
        get: operations["assignable_users_api_investigations_assignable_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation */
        get: operations["get_investigation_api_investigations__reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Investigation */
        patch: operations["update_investigation_api_investigations__reference__patch"];
        trace?: never;
    };
    "/api/investigations/{reference}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_investigations__reference__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_api_investigations__reference__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{reference}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Investigation Activity */
        get: operations["investigation_activity_api_investigations__reference__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence */
        get: operations["list_evidence_api_investigations__case_reference__evidence_get"];
        put?: never;
        /** Upload Evidence */
        post: operations["upload_evidence_api_investigations__case_reference__evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_investigations__case_reference__evidence__evidence_reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Original
         * @description The original file, always as a download (never rendered by the browser).
         */
        get: operations["download_original_api_investigations__case_reference__evidence__evidence_reference__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview
         * @description A derived JPEG preview (images only). The original is never served inline.
         */
        get: operations["preview_api_investigations__case_reference__evidence__evidence_reference__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}/verify-integrity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Integrity */
        post: operations["verify_integrity_api_investigations__case_reference__evidence__evidence_reference__verify_integrity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Status */
        post: operations["change_status_api_investigations__case_reference__evidence__evidence_reference__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocess */
        post: operations["reprocess_api_investigations__case_reference__evidence__evidence_reference__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence History */
        get: operations["evidence_history_api_investigations__case_reference__evidence__evidence_reference__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entities */
        get: operations["list_entities_api_investigations__case_reference__entities_get"];
        put?: never;
        /** Create Entity */
        post: operations["create_entity_api_investigations__case_reference__entities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/entities/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entity */
        get: operations["get_entity_api_investigations__case_reference__entities__reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/entities/{reference}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Entity */
        post: operations["review_entity_api_investigations__case_reference__entities__reference__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_investigations__case_reference__events_get"];
        put?: never;
        /** Create Event */
        post: operations["create_event_api_investigations__case_reference__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/events/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_investigations__case_reference__events__reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/events/{reference}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Event */
        post: operations["review_event_api_investigations__case_reference__events__reference__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}/extracted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Extracted Information */
        get: operations["extracted_information_api_investigations__case_reference__evidence__evidence_reference__extracted_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/correlations/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run */
        post: operations["run_api_investigations__case_reference__correlations_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/correlations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Correlations */
        get: operations["list_correlations_api_investigations__case_reference__correlations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/correlations/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Correlation */
        get: operations["get_correlation_api_investigations__case_reference__correlations__reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/correlations/{reference}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_api_investigations__case_reference__correlations__reference__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph */
        get: operations["get_graph_api_investigations__case_reference__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_ai_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/ai/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_investigations__case_reference__ai_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/evidence/{evidence_reference}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Similar */
        get: operations["similar_api_investigations__case_reference__evidence__evidence_reference__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/ai/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex */
        post: operations["reindex_api_investigations__case_reference__ai_reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_reference}/assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Streams newline-delimited JSON events: status, tool_start, tool_result, answer, error.
         */
        post: operations["ask_api_investigations__case_reference__assistant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIStatusOut */
        AIStatusOut: {
            /** Available */
            available: boolean;
            /** Chat Model */
            chat_model: string;
            /** Embed Model */
            embed_model: string;
            /** Chat Model Ready */
            chat_model_ready: boolean;
            /** Embed Model Ready */
            embed_model_ready: boolean;
            /** Message */
            message: string;
        };
        /** AskIn */
        AskIn: {
            /** Question */
            question: string;
            /** History */
            history?: components["schemas"]["Turn"][];
        };
        /** AssignableUser */
        AssignableUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /** AuditEntry */
        AuditEntry: {
            /** Id */
            id: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Actor Email */
            actor_email: string | null;
            /** Action */
            action: string;
            /** Object Type */
            object_type: string | null;
            /** Object Id */
            object_id: string | null;
            /** Previous State */
            previous_state: {
                [key: string]: unknown;
            } | null;
            /** New State */
            new_state: {
                [key: string]: unknown;
            } | null;
            /** Note */
            note: string | null;
            /** Ip Address */
            ip_address: string | null;
        };
        /** Body_upload_evidence_api_investigations__case_reference__evidence_post */
        Body_upload_evidence_api_investigations__case_reference__evidence_post: {
            /**
             * File
             * @description The evidence file
             */
            file: string;
            /**
             * Evidence Type
             * @enum {string}
             */
            evidence_type: "video" | "image" | "document" | "gps" | "mobile" | "call_records" | "financial" | "vehicle" | "witness_statement" | "digital_file" | "other";
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Collected At */
            collected_at?: string | null;
            /**
             * Location Text
             * @default
             */
            location_text: string;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Tags
             * @description Comma-separated
             * @default
             */
            tags: string;
        };
        /** CorrelationDetail */
        CorrelationDetail: {
            /** Reference */
            reference: string;
            evidence_a: components["schemas"]["EvidenceRef"];
            evidence_b: components["schemas"]["EvidenceRef"];
            /** Score */
            score: number;
            /**
             * Level
             * @enum {string}
             */
            level: "high" | "medium" | "low";
            /** Factors */
            factors: components["schemas"]["FactorOut"][];
            /** Algorithm */
            algorithm: string;
            /** Stale */
            stale: boolean;
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "pending" | "confirmed" | "rejected";
            /** Review Note */
            review_note: string | null;
            /** Reviewed By */
            reviewed_by: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Supporting Events */
            supporting_events: components["schemas"]["EventOut"][];
        };
        /** CorrelationOut */
        CorrelationOut: {
            /** Reference */
            reference: string;
            evidence_a: components["schemas"]["EvidenceRef"];
            evidence_b: components["schemas"]["EvidenceRef"];
            /** Score */
            score: number;
            /**
             * Level
             * @enum {string}
             */
            level: "high" | "medium" | "low";
            /** Factors */
            factors: components["schemas"]["FactorOut"][];
            /** Algorithm */
            algorithm: string;
            /** Stale */
            stale: boolean;
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "pending" | "confirmed" | "rejected";
            /** Review Note */
            review_note: string | null;
            /** Reviewed By */
            reviewed_by: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CorrelationPage */
        CorrelationPage: {
            /** Items */
            items: components["schemas"]["CorrelationOut"][];
            /** Total */
            total: number;
        };
        /** CurrentUserResponse */
        CurrentUserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Permissions */
            permissions: string[];
            /** Mfa Enabled */
            mfa_enabled: boolean;
            /**
             * Session Expires At
             * Format: date-time
             */
            session_expires_at: string;
        };
        /** DatabaseHealth */
        DatabaseHealth: {
            /** Connected */
            connected: boolean;
            /** Server Version */
            server_version?: string | null;
            /**
             * Extensions
             * @default {}
             */
            extensions: {
                [key: string]: string | null;
            };
        };
        /** EdgeOut */
        EdgeOut: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Type
             * @enum {string}
             */
            type: "appears_in" | "communicated_with" | "connected_to" | "related_evidence" | "involved_in" | "recorded_in";
            /** Why */
            why: string;
            /** Confidence */
            confidence: number;
            /** Review Status */
            review_status: string;
            /** Assertion Kinds */
            assertion_kinds: string[];
            /** Supporting Evidence */
            supporting_evidence: string[];
            /** Supporting Events */
            supporting_events: string[];
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** EntityBrief */
        EntityBrief: {
            /** Reference */
            reference: string;
            /** Entity Type */
            entity_type: string;
            /** Label */
            label: string;
            /** Review Status */
            review_status: string;
        };
        /** EntityCreate */
        EntityCreate: {
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "person" | "phone_number" | "device" | "vehicle" | "account" | "location" | "organization" | "digital_artifact";
            /** Value */
            value: string;
            /** Evidence Reference */
            evidence_reference: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** EntityDetail */
        EntityDetail: {
            /** Reference */
            reference: string;
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "person" | "phone_number" | "device" | "vehicle" | "account" | "location" | "organization" | "digital_artifact";
            /** Label */
            label: string;
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "pending" | "confirmed" | "rejected";
            /** Mention Count */
            mention_count: number;
            /** Evidence Count */
            evidence_count: number;
            /** Event Count */
            event_count: number;
            /** Max Confidence */
            max_confidence: number | null;
            /** Assertion Kinds */
            assertion_kinds: ("fact" | "extracted" | "detected" | "correlated" | "inferred" | "user_entered")[];
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
            /** Added Manually */
            added_manually: boolean;
            /** Mentions */
            mentions: components["schemas"]["MentionOut"][];
            /** Events */
            events: components["schemas"]["EventOut"][];
        };
        /** EntityMentionOut */
        EntityMentionOut: {
            entity: components["schemas"]["EntityRef"];
            /**
             * Assertion Kind
             * @enum {string}
             */
            assertion_kind: "fact" | "extracted" | "detected" | "correlated" | "inferred" | "user_entered";
            /** Confidence */
            confidence: number;
            /** Extractor */
            extractor: string;
            /** Source Location */
            source_location: string;
            /** Context */
            context: string;
        };
        /** EntityPage */
        EntityPage: {
            /** Items */
            items: components["schemas"]["EntitySummary"][];
            /** Total */
            total: number;
        };
        /** EntityRef */
        EntityRef: {
            /** Reference */
            reference: string;
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "person" | "phone_number" | "device" | "vehicle" | "account" | "location" | "organization" | "digital_artifact";
            /** Label */
            label: string;
        };
        /** EntitySummary */
        EntitySummary: {
            /** Reference */
            reference: string;
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "person" | "phone_number" | "device" | "vehicle" | "account" | "location" | "organization" | "digital_artifact";
            /** Label */
            label: string;
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "pending" | "confirmed" | "rejected";
            /** Mention Count */
            mention_count: number;
            /** Evidence Count */
            evidence_count: number;
            /** Event Count */
            event_count: number;
            /** Max Confidence */
            max_confidence: number | null;
            /** Assertion Kinds */
            assertion_kinds: ("fact" | "extracted" | "detected" | "correlated" | "inferred" | "user_entered")[];
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
            /** Added Manually */
            added_manually: boolean;
        };
        /** EventCreate */
        EventCreate: {
            /** Evidence Reference */
            evidence_reference: string;
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "call_made" | "message_sent" | "transaction_completed" | "location_recorded" | "vehicle_detected" | "person_detected" | "device_detected" | "person_entered_location" | "photo_taken" | "video_recorded" | "document_created" | "communication" | "digital_artifact_created" | "other";
            /** Occurred At */
            occurred_at?: string | null;
            /** Description */
            description: string;
            /** Participants */
            participants?: components["schemas"]["ParticipantIn"][];
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Location Text
             * @default
             */
            location_text: string;
        };
        /** EventOut */
        EventOut: {
            /** Reference */
            reference: string;
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "call_made" | "message_sent" | "transaction_completed" | "location_recorded" | "vehicle_detected" | "person_detected" | "device_detected" | "person_entered_location" | "photo_taken" | "video_recorded" | "document_created" | "communication" | "digital_artifact_created" | "other";
            /** Occurred At */
            occurred_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            /** Location Text */
            location_text: string;
            /** Description */
            description: string;
            /** Evidence Reference */
            evidence_reference: string;
            /** Evidence Type */
            evidence_type: string;
            /**
             * Assertion Kind
             * @enum {string}
             */
            assertion_kind: "fact" | "extracted" | "detected" | "correlated" | "inferred" | "user_entered";
            /** Confidence */
            confidence: number;
            /** Extractor */
            extractor: string;
            /** Source Location */
            source_location: string;
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "pending" | "confirmed" | "rejected";
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
            /** Participants */
            participants: components["schemas"]["Participant"][];
            /** Added Manually */
            added_manually: boolean;
        };
        /** EventPage */
        EventPage: {
            /** Items */
            items: components["schemas"]["EventOut"][];
            /** Total */
            total: number;
        };
        /** EvidenceBrief */
        EvidenceBrief: {
            /** Reference */
            reference: string;
            /** Evidence Type */
            evidence_type: string;
            /** Description */
            description: string;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Reference */
            reference: string;
            /** Investigation Reference */
            investigation_reference: string;
            /**
             * Evidence Type
             * @enum {string}
             */
            evidence_type: "video" | "image" | "document" | "gps" | "mobile" | "call_records" | "financial" | "vehicle" | "witness_statement" | "digital_file" | "other";
            /**
             * Status
             * @enum {string}
             */
            status: "uploaded" | "processing" | "processed" | "verified" | "requires_review" | "archived";
            /** Source */
            source: string;
            /** Description */
            description: string;
            /** Collected At */
            collected_at: string | null;
            /** Location Text */
            location_text: string;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            /** Tags */
            tags: string[];
            /** Original Filename */
            original_filename: string;
            /** Media Type */
            media_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /** Integrity Checked At */
            integrity_checked_at: string | null;
            /** Integrity Ok */
            integrity_ok: boolean | null;
            /** Has Preview */
            has_preview: boolean;
            /** File Metadata */
            file_metadata: {
                [key: string]: unknown;
            };
            /** Uploaded By */
            uploaded_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            latest_job: components["schemas"]["JobOut"] | null;
        };
        /** EvidencePage */
        EvidencePage: {
            /** Items */
            items: components["schemas"]["EvidenceOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** EvidenceRef */
        EvidenceRef: {
            /** Reference */
            reference: string;
            /** Evidence Type */
            evidence_type: string;
            /** Description */
            description: string;
        };
        /** ExtractedInformation */
        ExtractedInformation: {
            /** Evidence Reference */
            evidence_reference: string;
            /** Mentions */
            mentions: components["schemas"]["EntityMentionOut"][];
            /** Events */
            events: components["schemas"]["EventOut"][];
        };
        /** FactorOut */
        FactorOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "entity" | "time" | "location";
            /** Score */
            score: number;
            /** Weight */
            weight: number;
            /** Contribution */
            contribution: number;
            /** Explanation */
            explanation: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** GraphOut */
        GraphOut: {
            /** Nodes */
            nodes: components["schemas"]["NodeOut"][];
            /** Edges */
            edges: components["schemas"]["EdgeOut"][];
            /** Total Nodes */
            total_nodes: number;
            /** Total Edges */
            total_edges: number;
            /** Truncated */
            truncated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            database: components["schemas"]["DatabaseHealth"];
        };
        /**
         * InvestigationCounts
         * @description Filled in as later phases add evidence (P5), entities/events (P6), correlations (P8).
         */
        InvestigationCounts: {
            /**
             * Evidence
             * @default 0
             */
            evidence: number;
            /**
             * Entities
             * @default 0
             */
            entities: number;
            /**
             * Events
             * @default 0
             */
            events: number;
            /**
             * Correlations
             * @default 0
             */
            correlations: number;
        };
        /** InvestigationCreate */
        InvestigationCreate: {
            /** Title */
            title: string;
            /** Case Type */
            case_type: string;
            /**
             * Priority
             * @default medium
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "critical";
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Time Zone
             * @default UTC
             */
            time_zone: string;
            /** Tags */
            tags?: string[];
        };
        /** InvestigationOut */
        InvestigationOut: {
            /** Reference */
            reference: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Case Type */
            case_type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "active" | "under_review" | "suspended" | "closed" | "archived";
            /**
             * Priority
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "critical";
            /**
             * Stage
             * @enum {string}
             */
            stage: "intake" | "processing" | "extraction" | "correlation" | "review" | "reporting" | "closed";
            /** Location */
            location: string;
            /** Time Zone */
            time_zone: string;
            /** Tags */
            tags: string[];
            lead_investigator: components["schemas"]["PersonRef"];
            /** Team Size */
            team_size: number;
            /** My Role In Case */
            my_role_in_case: ("lead" | "member") | null;
            counts: components["schemas"]["InvestigationCounts"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** InvestigationPage */
        InvestigationPage: {
            /** Items */
            items: components["schemas"]["InvestigationOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** InvestigationUpdate */
        InvestigationUpdate: {
            /** Title */
            title?: string | null;
            /** Case Type */
            case_type?: string | null;
            /** Priority */
            priority?: ("low" | "medium" | "high" | "critical") | null;
            /** Status */
            status?: ("draft" | "active" | "under_review" | "suspended" | "closed" | "archived") | null;
            /** Stage */
            stage?: ("intake" | "processing" | "extraction" | "correlation" | "review" | "reporting" | "closed") | null;
            /** Location */
            location?: string | null;
            /** Description */
            description?: string | null;
            /** Time Zone */
            time_zone?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Progress */
            progress: number;
            /** Current Step */
            current_step: string | null;
            /** Steps */
            steps: components["schemas"]["JobStep"][];
            /** Attempts */
            attempts: number;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** JobStep */
        JobStep: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Duration Ms */
            duration_ms: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Remember
             * @default false
             */
            remember: boolean;
        };
        /** MemberAdd */
        MemberAdd: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** MemberOut */
        MemberOut: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /**
             * Role In Case
             * @enum {string}
             */
            role_in_case: "lead" | "member";
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
        };
        /** MentionOut */
        MentionOut: {
            /** Evidence Reference */
            evidence_reference: string;
            /** Evidence Type */
            evidence_type: string;
            /** Evidence Description */
            evidence_description: string;
            /**
             * Assertion Kind
             * @enum {string}
             */
            assertion_kind: "fact" | "extracted" | "detected" | "correlated" | "inferred" | "user_entered";
            /** Confidence */
            confidence: number;
            /** Extractor */
            extractor: string;
            /** Source Location */
            source_location: string;
            /** Context */
            context: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NodeOut */
        NodeOut: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "entity" | "evidence" | "event";
            /** Type */
            type: string;
            /** Reference */
            reference: string;
            /** Label */
            label: string;
            /** Review Status */
            review_status: string | null;
            /** Degree */
            degree: number;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** Participant */
        Participant: {
            /** Reference */
            reference: string;
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "person" | "phone_number" | "device" | "vehicle" | "account" | "location" | "organization" | "digital_artifact";
            /** Label */
            label: string;
            /** Role */
            role: string;
        };
        /** ParticipantIn */
        ParticipantIn: {
            /** Entity Reference */
            entity_reference: string;
            /**
             * Role
             * @default involved
             */
            role: string;
        };
        /** Passage */
        Passage: {
            evidence: components["schemas"]["EvidenceBrief"];
            /** Score */
            score: number;
            /** Passage */
            passage: string;
        };
        /** PersonRef */
        PersonRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
        };
        /** ReindexOut */
        ReindexOut: {
            /** Documents */
            documents: number;
            /** Chunks */
            chunks: number;
            /** Images */
            images: number;
        };
        /** Review */
        Review: {
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "pending" | "confirmed" | "rejected";
            /** Note */
            note?: string | null;
        };
        /** RunResult */
        RunResult: {
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Removed */
            removed: number;
            /** Stale */
            stale: number;
            /** Total */
            total: number;
        };
        /** SearchIn */
        SearchIn: {
            /** Question */
            question: string;
        };
        /** SearchOut */
        SearchOut: {
            /** Question */
            question: string;
            plan: components["schemas"]["SearchPlan"];
            /** Summary */
            summary: string;
            /** Notes */
            notes: string[];
            /** Interpreted By */
            interpreted_by: string;
            /** Duration Ms */
            duration_ms: number;
            /** Events */
            events: components["schemas"]["EventOut"][];
            /** Evidence */
            evidence: components["schemas"]["EvidenceBrief"][];
            /** Entities */
            entities: components["schemas"]["EntityBrief"][];
            /** Path */
            path: components["schemas"]["EdgeOut"][];
            /** Path Nodes */
            path_nodes: components["schemas"]["NodeOut"][];
            /** Passages */
            passages: components["schemas"]["Passage"][];
        };
        /** SearchPlan */
        SearchPlan: {
            /**
             * Intent
             * @description events = things that happened; evidence = files; entities = people, phones, vehicles…; connection = how two items are linked; text = find passages about a topic in documents
             * @enum {string}
             */
            intent: "events" | "evidence" | "entities" | "connection" | "text";
            /**
             * Entity Refs
             * @description IDs like P001, V001
             */
            entity_refs?: string[];
            /**
             * Evidence Refs
             * @description IDs like CCTV-001
             */
            evidence_refs?: string[];
            /** Event Types */
            event_types?: string[];
            /** Evidence Types */
            evidence_types?: string[];
            /** Entity Types */
            entity_types?: string[];
            /**
             * Date From
             * @description YYYY-MM-DD
             */
            date_from?: string | null;
            /**
             * Date To
             * @description YYYY-MM-DD
             */
            date_to?: string | null;
            /**
             * Time From
             * @description HH:MM, 24-hour, time of day
             */
            time_from?: string | null;
            /**
             * Time To
             * @description HH:MM, 24-hour, time of day
             */
            time_to?: string | null;
            /**
             * Text
             * @description topic words to look for in documents
             */
            text?: string | null;
        };
        /** SimilarOut */
        SimilarOut: {
            evidence: components["schemas"]["EvidenceBrief"];
            /**
             * Kind
             * @enum {string}
             */
            kind: "image" | "text";
            /** Score */
            score: number;
            /** Explanation */
            explanation: string;
            /** Passage */
            passage: string;
            /** Match */
            match: string;
        };
        /** StatusChange */
        StatusChange: {
            /**
             * Status
             * @enum {string}
             */
            status: "processed" | "verified" | "requires_review";
            /** Note */
            note?: string | null;
        };
        /** Turn */
        Turn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** UserSummary */
        UserSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Mfa Enabled */
            mfa_enabled: boolean;
            /** Locked */
            locked: boolean;
            /** Last Login At */
            last_login_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"][];
                };
            };
        };
    };
    list_audit_entries_api_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigations_api_investigations_get: {
        parameters: {
            query?: {
                search?: string | null;
                status?: ("draft" | "active" | "under_review" | "suspended" | "closed" | "archived") | null;
                priority?: ("low" | "medium" | "high" | "critical") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_investigation_api_investigations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assignable_users_api_investigations_assignable_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignableUser"][];
                };
            };
        };
    };
    get_investigation_api_investigations__reference__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_investigation_api_investigations__reference__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_investigations__reference__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_investigations__reference__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investigation_activity_api_investigations__reference__activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_api_investigations__case_reference__evidence_get: {
        parameters: {
            query?: {
                search?: string | null;
                evidence_type?: ("video" | "image" | "document" | "gps" | "mobile" | "call_records" | "financial" | "vehicle" | "witness_statement" | "digital_file" | "other") | null;
                status?: ("uploaded" | "processing" | "processed" | "verified" | "requires_review" | "archived") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                case_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_evidence_api_investigations__case_reference__evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_evidence_api_investigations__case_reference__evidence_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_investigations__case_reference__evidence__evidence_reference__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_original_api_investigations__case_reference__evidence__evidence_reference__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_investigations__case_reference__evidence__evidence_reference__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_integrity_api_investigations__case_reference__evidence__evidence_reference__verify_integrity_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_api_investigations__case_reference__evidence__evidence_reference__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_api_investigations__case_reference__evidence__evidence_reference__reprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_history_api_investigations__case_reference__evidence__evidence_reference__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities_api_investigations__case_reference__entities_get: {
        parameters: {
            query?: {
                entity_type?: ("person" | "phone_number" | "device" | "vehicle" | "account" | "location" | "organization" | "digital_artifact") | null;
                search?: string | null;
                review_status?: ("pending" | "confirmed" | "rejected") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                case_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entity_api_investigations__case_reference__entities_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_api_investigations__case_reference__entities__reference__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_entity_api_investigations__case_reference__entities__reference__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Review"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_investigations__case_reference__events_get: {
        parameters: {
            query?: {
                /** @description Repeat for several */
                event_type?: ("call_made" | "message_sent" | "transaction_completed" | "location_recorded" | "vehicle_detected" | "person_detected" | "device_detected" | "person_entered_location" | "photo_taken" | "video_recorded" | "document_created" | "communication" | "digital_artifact_created" | "other")[] | null;
                entity?: string | null;
                evidence?: string | null;
                evidence_type?: string | null;
                occurred_from?: string | null;
                occurred_to?: string | null;
                review_status?: ("pending" | "confirmed" | "rejected") | null;
                has_location?: boolean | null;
                near_lat?: number | null;
                near_lon?: number | null;
                radius_m?: number;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                case_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_api_investigations__case_reference__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_investigations__case_reference__events__reference__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_event_api_investigations__case_reference__events__reference__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Review"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extracted_information_api_investigations__case_reference__evidence__evidence_reference__extracted_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractedInformation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_investigations__case_reference__correlations_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_correlations_api_investigations__case_reference__correlations_get: {
        parameters: {
            query?: {
                level?: ("high" | "medium" | "low") | null;
                review_status?: ("pending" | "confirmed" | "rejected") | null;
                evidence?: string | null;
                include_stale?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                case_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_correlation_api_investigations__case_reference__correlations__reference__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_investigations__case_reference__correlations__reference__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Review"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_investigations__case_reference__graph_get: {
        parameters: {
            query?: {
                include_events?: boolean;
                include_evidence?: boolean;
                include_rejected?: boolean;
                include_stale?: boolean;
                entity_type?: string[] | null;
                min_level?: "low" | "medium" | "high";
                focus?: string | null;
                depth?: number;
                max_nodes?: number;
            };
            header?: never;
            path: {
                case_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_ai_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIStatusOut"];
                };
            };
        };
    };
    search_api_investigations__case_reference__ai_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_api_investigations__case_reference__evidence__evidence_reference__similar_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
                evidence_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_api_investigations__case_reference__ai_reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_investigations__case_reference__assistant_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
