/**
 * Friendly names for the API shapes generated from the backend's OpenAPI document.
 * Regenerate after backend changes:  npm run api:types   (backend must be running)
 */
import type { components } from './schema'

type Schemas = components['schemas']

export type InvestigationDto = Schemas['InvestigationOut']
export type InvestigationPageDto = Schemas['InvestigationPage']
export type InvestigationCreateDto = Schemas['InvestigationCreate']
export type InvestigationUpdateDto = Schemas['InvestigationUpdate']
export type MemberDto = Schemas['MemberOut']
export type AssignableUserDto = Schemas['AssignableUser']
export type AuditEntryDto = Schemas['AuditEntry']
export type EvidenceDto = Schemas['EvidenceOut']
export type EvidencePageDto = Schemas['EvidencePage']
export type JobDto = Schemas['JobOut']
export type EntitySummaryDto = Schemas['EntitySummary']
export type EntityDetailDto = Schemas['EntityDetail']
export type EntityPageDto = Schemas['EntityPage']
export type MentionDto = Schemas['MentionOut']
export type EventDto = Schemas['EventOut']
export type EventPageDto = Schemas['EventPage']
export type ExtractedInformationDto = Schemas['ExtractedInformation']
export type EntityCreateDto = Schemas['EntityCreate']
export type EventCreateDto = Schemas['EventCreate']
export type CorrelationDto = Schemas['CorrelationOut']
export type CorrelationDetailDto = Schemas['CorrelationDetail']
export type CorrelationPageDto = Schemas['CorrelationPage']
export type CorrelationRunDto = Schemas['RunResult']
export type GraphDto = Schemas['GraphOut']
export type GraphNodeDto = Schemas['NodeOut']
export type GraphEdgeDto = Schemas['EdgeOut']
export type AIStatusDto = Schemas['AIStatusOut']
export type AISearchDto = Schemas['SearchOut']
export type SimilarDto = Schemas['SimilarOut']
export type ReindexDto = Schemas['ReindexOut']
export type TaskDto = Schemas['TaskOut']
export type NotificationDto = Schemas['NotificationOut']
export type NotificationPageDto = Schemas['NotificationPage']
export type ReportSummaryDto = Schemas['ReportSummary']
export type ReportDetailDto = Schemas['ReportDetail']
export type DashboardDto = Schemas['DashboardOut']
export type SearchHitDto = Schemas['SearchHit']
