"""correlations

Revision ID: 98741a265b96
Revises: a231b52d88ed
Create Date: 2026-10-02 17:00:14.329273

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "98741a265b96"
down_revision: str | Sequence[str] | None = "a231b52d88ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "correlations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("investigation_id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=12), nullable=False),
        sa.Column("evidence_a_id", sa.UUID(), nullable=False),
        sa.Column("evidence_b_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("algorithm", sa.String(length=30), nullable=False),
        sa.Column("stale", sa.Boolean(), nullable=False),
        sa.Column("review_status", sa.String(length=12), nullable=False),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("reviewed_by_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "level IN ('high', 'medium', 'low')", name=op.f("ck_correlations_valid_level")
        ),
        sa.CheckConstraint(
            "review_status IN ('pending', 'confirmed', 'rejected')",
            name=op.f("ck_correlations_valid_review_status"),
        ),
        sa.CheckConstraint(
            "evidence_a_id <> evidence_b_id", name=op.f("ck_correlations_two_different_items")
        ),
        sa.CheckConstraint("score BETWEEN 0 AND 1", name=op.f("ck_correlations_valid_score")),
        sa.ForeignKeyConstraint(
            ["evidence_a_id"],
            ["evidence.id"],
            name=op.f("fk_correlations_evidence_a_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_b_id"],
            ["evidence.id"],
            name=op.f("fk_correlations_evidence_b_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_correlations_investigation_id_investigations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"], ["users.id"], name=op.f("fk_correlations_reviewed_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_correlations")),
        sa.UniqueConstraint(
            "investigation_id", "evidence_a_id", "evidence_b_id", name="one_per_pair"
        ),
        sa.UniqueConstraint("investigation_id", "reference", name="correlation_reference_per_case"),
    )
    op.create_index(
        op.f("ix_correlations_evidence_a_id"), "correlations", ["evidence_a_id"], unique=False
    )
    op.create_index(
        op.f("ix_correlations_evidence_b_id"), "correlations", ["evidence_b_id"], unique=False
    )
    op.create_index(
        op.f("ix_correlations_investigation_id"), "correlations", ["investigation_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_correlations_investigation_id"), table_name="correlations")
    op.drop_index(op.f("ix_correlations_evidence_b_id"), table_name="correlations")
    op.drop_index(op.f("ix_correlations_evidence_a_id"), table_name="correlations")
    op.drop_table("correlations")
    # ### end Alembic commands ###
