"""entities and events

Revision ID: 9ced556d0158
Revises: e5af13eea2f7
Create Date: 2026-10-02 13:52:44.869611

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9ced556d0158"
down_revision: str | Sequence[str] | None = "e5af13eea2f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("investigation_id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=12), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("normalized_key", sa.String(length=200), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("review_status", sa.String(length=12), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_type IN ('person', 'phone_number', 'device', 'vehicle', 'account', 'location', 'organization', 'digital_artifact')",
            name=op.f("ck_entities_valid_type"),
        ),
        sa.CheckConstraint(
            "review_status IN ('pending', 'confirmed', 'rejected')",
            name=op.f("ck_entities_valid_review_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_entities_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_entities_investigation_id_investigations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
        sa.UniqueConstraint(
            "investigation_id", "entity_type", "normalized_key", name="one_per_identifier"
        ),
        sa.UniqueConstraint("investigation_id", "reference", name="entity_reference_per_case"),
    )
    op.create_index(
        op.f("ix_entities_investigation_id"), "entities", ["investigation_id"], unique=False
    )
    op.create_table(
        "entity_mentions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("assertion_kind", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("extractor", sa.String(length=60), nullable=False),
        sa.Column("source_location", sa.String(length=120), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "assertion_kind IN ('fact', 'extracted', 'detected', 'correlated', 'inferred', 'user_entered')",
            name=op.f("ck_entity_mentions_valid_assertion"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_entity_mentions_valid_confidence")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_entity_mentions_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_entity_mentions_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_entity_mentions_evidence_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_mentions")),
    )
    op.create_index(
        op.f("ix_entity_mentions_entity_id"), "entity_mentions", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_entity_mentions_evidence_id"), "entity_mentions", ["evidence_id"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("investigation_id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=12), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("location_text", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("assertion_kind", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("extractor", sa.String(length=60), nullable=False),
        sa.Column("source_location", sa.String(length=120), nullable=False),
        sa.Column("review_status", sa.String(length=12), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "assertion_kind IN ('fact', 'extracted', 'detected', 'correlated', 'inferred', 'user_entered')",
            name=op.f("ck_events_valid_assertion"),
        ),
        sa.CheckConstraint(
            "event_type IN ('call_made', 'message_sent', 'transaction_completed', 'location_recorded', 'vehicle_detected', 'person_detected', 'device_detected', 'person_entered_location', 'photo_taken', 'video_recorded', 'document_created', 'communication', 'digital_artifact_created', 'other')",
            name=op.f("ck_events_valid_type"),
        ),
        sa.CheckConstraint(
            "review_status IN ('pending', 'confirmed', 'rejected')",
            name=op.f("ck_events_valid_review_status"),
        ),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name=op.f("ck_events_valid_confidence")),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_events_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_events_evidence_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_events_investigation_id_investigations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("investigation_id", "reference", name="event_reference_per_case"),
    )
    op.create_index(
        "ix_events_case_time", "events", ["investigation_id", "occurred_at"], unique=False
    )
    op.create_index(op.f("ix_events_evidence_id"), "events", ["evidence_id"], unique=False)
    op.create_index(
        op.f("ix_events_investigation_id"), "events", ["investigation_id"], unique=False
    )
    op.create_table(
        "event_participants",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_event_participants_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_participants_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "event_id", "entity_id", "role", name=op.f("pk_event_participants")
        ),
    )
    op.create_index(
        op.f("ix_event_participants_entity_id"), "event_participants", ["entity_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_event_participants_entity_id"), table_name="event_participants")
    op.drop_table("event_participants")
    op.drop_index(op.f("ix_events_investigation_id"), table_name="events")
    op.drop_index(op.f("ix_events_evidence_id"), table_name="events")
    op.drop_index("ix_events_case_time", table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_entity_mentions_evidence_id"), table_name="entity_mentions")
    op.drop_index(op.f("ix_entity_mentions_entity_id"), table_name="entity_mentions")
    op.drop_table("entity_mentions")
    op.drop_index(op.f("ix_entities_investigation_id"), table_name="entities")
    op.drop_table("entities")
    # ### end Alembic commands ###
