"""correlation refresh requests

Revision ID: 337e0b8429ff
Revises: 552f99b734d0
Create Date: 2026-10-03 18:33:16.489996

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "337e0b8429ff"
down_revision: str | Sequence[str] | None = "552f99b734d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investigations",
        sa.Column("correlation_requested_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("investigations", "correlation_requested_at")
    # ### end Alembic commands ###
