"""investigation time zone

Revision ID: a231b52d88ed
Revises: 9ced556d0158
Create Date: 2026-10-02 15:41:10.171977

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a231b52d88ed"
down_revision: str | Sequence[str] | None = "9ced556d0158"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investigations",
        sa.Column("time_zone", sa.String(length=64), server_default="UTC", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("investigations", "time_zone")
    # ### end Alembic commands ###
