"""mfa

Revision ID: 552f99b734d0
Revises: 7db8318936d4
Create Date: 2026-10-02 21:03:12.494493

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "552f99b734d0"
down_revision: str | Sequence[str] | None = "7db8318936d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_sessions",
        sa.Column("mfa_pending", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "user_sessions", sa.Column("remember", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("users", sa.Column("mfa_secret", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("mfa_pending_secret", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("mfa_last_step", sa.BigInteger(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "mfa_recovery_hashes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "mfa_recovery_hashes")
    op.drop_column("users", "mfa_last_step")
    op.drop_column("users", "mfa_pending_secret")
    op.drop_column("users", "mfa_secret")
    op.drop_column("user_sessions", "remember")
    op.drop_column("user_sessions", "mfa_pending")
    # ### end Alembic commands ###
