"""ai similarity index

Revision ID: ecc19afb6027
Revises: 98741a265b96
Create Date: 2026-10-02 18:43:52.666553

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecc19afb6027"
down_revision: str | Sequence[str] | None = "98741a265b96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("investigation_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_evidence_chunks_evidence_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_evidence_chunks_investigation_id_investigations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_chunks")),
    )
    op.create_index(
        "ix_evidence_chunks_embedding",
        "evidence_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_evidence_chunks_evidence_id"), "evidence_chunks", ["evidence_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_chunks_investigation_id"),
        "evidence_chunks",
        ["investigation_id"],
        unique=False,
    )
    op.add_column("evidence", sa.Column("perceptual_hash", sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evidence", "perceptual_hash")
    op.drop_index(op.f("ix_evidence_chunks_investigation_id"), table_name="evidence_chunks")
    op.drop_index(op.f("ix_evidence_chunks_evidence_id"), table_name="evidence_chunks")
    op.drop_index(
        "ix_evidence_chunks_embedding",
        table_name="evidence_chunks",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("evidence_chunks")
    # ### end Alembic commands ###
