"""evidence and processing jobs

Revision ID: e5af13eea2f7
Revises: 77dc600bf524
Create Date: 2026-10-02 13:00:18.910935

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e5af13eea2f7"
down_revision: str | Sequence[str] | None = "77dc600bf524"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("investigation_id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=20), nullable=False),
        sa.Column("evidence_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location_text", sa.String(length=200), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=300), nullable=False),
        sa.Column("integrity_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("integrity_ok", sa.Boolean(), nullable=True),
        sa.Column("file_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("preview_key", sa.String(length=300), nullable=True),
        sa.Column("uploaded_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "evidence_type IN ('video', 'image', 'document', 'gps', 'mobile', 'call_records', 'financial', 'vehicle', 'witness_statement', 'digital_file', 'other')",
            name=op.f("ck_evidence_valid_type"),
        ),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_evidence_sha256_hex")),
        sa.CheckConstraint(
            "status IN ('uploaded', 'processing', 'processed', 'verified', 'requires_review', 'archived')",
            name=op.f("ck_evidence_valid_status"),
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_evidence_non_negative_size")),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_evidence_investigation_id_investigations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"], ["users.id"], name=op.f("fk_evidence_uploaded_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint("investigation_id", "reference", name="reference_per_case"),
        sa.UniqueConstraint("investigation_id", "sha256", name="one_copy_per_case"),
        sa.UniqueConstraint("storage_key", name=op.f("uq_evidence_storage_key")),
    )
    op.create_index(op.f("ix_evidence_created_at"), "evidence", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_evidence_investigation_id"), "evidence", ["investigation_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_status"), "evidence", ["status"], unique=False)
    op.create_table(
        "evidence_reference_counters",
        sa.Column("investigation_id", sa.UUID(), nullable=False),
        sa.Column("prefix", sa.String(length=8), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_evidence_reference_counters_investigation_id_investigations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "investigation_id", "prefix", name=op.f("pk_evidence_reference_counters")
        ),
    )
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("current_step", sa.String(length=80), nullable=True),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("worker_id", sa.String(length=80), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed')",
            name=op.f("ck_processing_jobs_valid_status"),
        ),
        sa.CheckConstraint(
            "progress BETWEEN 0 AND 100", name=op.f("ck_processing_jobs_valid_progress")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_processing_jobs_evidence_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
    )
    op.create_index(
        op.f("ix_processing_jobs_created_at"), "processing_jobs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_processing_jobs_evidence_id"), "processing_jobs", ["evidence_id"], unique=False
    )
    op.create_index(
        "ix_processing_jobs_queue",
        "processing_jobs",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_processing_jobs_queue",
        table_name="processing_jobs",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_index(op.f("ix_processing_jobs_evidence_id"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_created_at"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_table("evidence_reference_counters")
    op.drop_index(op.f("ix_evidence_status"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_investigation_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_created_at"), table_name="evidence")
    op.drop_table("evidence")
    # ### end Alembic commands ###
