"""investigations and members

Revision ID: 77dc600bf524
Revises: e0d1f9c4dd5c
Create Date: 2026-09-30 23:50:57.764064

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "77dc600bf524"
down_revision: str | Sequence[str] | None = "e0d1f9c4dd5c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investigation_reference_counters",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("year", name=op.f("pk_investigation_reference_counters")),
    )
    op.create_table(
        "investigations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("case_type", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("lead_investigator_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'medium', 'high', 'critical')",
            name=op.f("ck_investigations_valid_priority"),
        ),
        sa.CheckConstraint(
            "stage IN ('intake', 'processing', 'extraction', 'correlation', 'review', 'reporting', 'closed')",
            name=op.f("ck_investigations_valid_stage"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'under_review', 'suspended', 'closed', 'archived')",
            name=op.f("ck_investigations_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_investigations_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["lead_investigator_id"],
            ["users.id"],
            name=op.f("fk_investigations_lead_investigator_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigations")),
    )
    op.create_index(
        op.f("ix_investigations_lead_investigator_id"),
        "investigations",
        ["lead_investigator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investigations_priority"), "investigations", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_investigations_reference"), "investigations", ["reference"], unique=True
    )
    op.create_index(op.f("ix_investigations_status"), "investigations", ["status"], unique=False)
    op.create_index(
        op.f("ix_investigations_updated_at"), "investigations", ["updated_at"], unique=False
    )
    op.create_table(
        "investigation_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("investigation_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_in_case", sa.String(length=10), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "role_in_case IN ('lead', 'member')",
            name=op.f("ck_investigation_members_valid_role_in_case"),
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_investigation_members_investigation_id_investigations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_investigation_members_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigation_members")),
        sa.UniqueConstraint("investigation_id", "user_id", name="one_membership"),
    )
    op.create_index(
        op.f("ix_investigation_members_investigation_id"),
        "investigation_members",
        ["investigation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investigation_members_user_id"), "investigation_members", ["user_id"], unique=False
    )
    # ### end Alembic commands ###

    # Fast "contains" / fuzzy search on titles (pg_trgm, enabled in Phase 0).
    op.execute(
        "CREATE INDEX ix_investigations_title_trgm ON investigations USING gin (title gin_trgm_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_investigations_title_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_investigation_members_user_id"), table_name="investigation_members")
    op.drop_index(
        op.f("ix_investigation_members_investigation_id"), table_name="investigation_members"
    )
    op.drop_table("investigation_members")
    op.drop_index(op.f("ix_investigations_updated_at"), table_name="investigations")
    op.drop_index(op.f("ix_investigations_status"), table_name="investigations")
    op.drop_index(op.f("ix_investigations_reference"), table_name="investigations")
    op.drop_index(op.f("ix_investigations_priority"), table_name="investigations")
    op.drop_index(op.f("ix_investigations_lead_investigator_id"), table_name="investigations")
    op.drop_table("investigations")
    op.drop_table("investigation_reference_counters")
    # ### end Alembic commands ###
